config/routes.rb
Rails.application.routes.draw do
# root to: 'users#index'
# root to: 'devise/sessions#index'
  
  devise_for :users
  devise_scope :user do
    
  authenticated :user do
    root 'home#index' , as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
    end
end

  
  resources :users
  resources :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
    
  validates :name, presence: true
  validates :price, presence: true
    
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :color, :price, :year, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!

  def index
    
  end

  def show
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    #@user = User.find(params[:id])
    #unless @user == current_user
      #redirect_to :back, :alert => "Access denied."
    #end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
                                
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :maxlength=>"40" %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  
  <div>
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
  <td><%= link_to 'Apagar', @car, method: :delete, data: { confirm: 'Você tem certeza disto? <br /> Esta exclusão é irreversivel.' } %></td>
  
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Price</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.color %></td>
        <td><%= car.price %></td>
        <td><%= car.year %></td>
        <td><%= link_to 'Visualizar', car %></td>
        <td><%= link_to 'Editar', edit_car_path(car) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<table style="width:100%">
  <tr>
    <td>
      <p>
        <strong>Name:</strong>
        <%= @car.name %>
      </p>
      <p>
        <strong>Color:</strong>
        <%= @car.color %>
      </p>
      <p>
        <strong>Price:</strong>
        <%= @car.price %>
      </p>
      <p>
        <strong>Year:</strong>
        <%= @car.year %>
      </p>
    </td>
    <td>
      <p>
        <strong>Foto:</strong>
        <%= image_tag @car.avatar.url(:medium) %>
      </p>
    </td>
  </tr>
</table>

<%= link_to 'Editar', edit_car_path(@car) %> |
<%= link_to 'Voltar', cars_path %>

app/views/home/index.html.erb
<html>
<head>
  <meta http-equiv="refresh" content="0; url=https://concess-gmascb.c9users.io/pages/about"/>
	<title></title>
</head>
<body>

</body>
</html>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? "success" : "alert" %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Editar Conta', edit_user_registration_path %></li>
  <li><%= link_to 'Carros', cars_path %></li>
  <li><%= link_to 'Usuários', users_path %></li>
<% else %>
  <li><%= link_to 'Registrar', new_user_registration_path %></li>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Deslogar', destroy_user_session_path, :method=>'delete' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<nav class="top-bar">
  <ul class="title-area">
    
    

    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Home', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Workspace" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Workspace" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<br/><p>Bem vindo a SConcess</p>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

app/views/users/_user.html.erb
<td><%= user.name  %></td>
<td><%= user.email %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/visitors/_visitors.html.erb
<h1>Bem Vindo a Concessionária Benaia</h1>
<!-- <p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p> -->

<p>Carros: <%= Car.count %> cadastrados </p>